### ISSUE TITLE
Error detected while processing function vimple#version#new

### ISSUE THREAD

**Issue by serussell** [dahu/vim-asciidoc#18]
vimple: commit b6cef6ef16bcd4e5bd0e07eeb102704ed1f2a47d
vim-asciidoc: commit 3dfab0902a34b0e099b7beaeba954bb356f90b23
neovim: v0.3.1

Vimple appears to be causing more problems.  I'm getting this on start-up:

```
Error detected while processing function vimple#version#new[75]..55:
line    4:
E688: More targets than List items
```

Is there any way to remove the dependency on vimple?

**Comment by dahu** [comment]
I don't have the time at the moment to look at excising vimple from vim-asciidoc, however you might find some joy in disabling the pieces you don't use:

to turn off all of the extra lib stuff, add a line like this to your vimrc:

    let g:vimple_init_vars = 1

Otherwise, if there are pieces you use, turn the pieces on and off specifically:

    let g:vimple_init_vars = 1
    let g:init_vimple_maps_and_commands = 1
    let g:vimple_init_ab = 0
    let g:vimple_init_bl = 1
    let g:vimple_init_hl = 0
    let g:vimple_init_sn = 0
    let g:vimple_init_vn = 0
    let g:vimple_init_ma = 1
    let g:vimple_init_ul = 0
    let g:vimple_init_mp = 1

These guard names are used in `plugin/vimple-lib.vim`, starting at line 339.

**Comment by serussell** [comment]
Unfortunately, the error is in the initialization, when vimple is trying to parse the NVIM version number; the regexp doesn't work with the version of neovim that's in Arch.

I also submitted a ticket to the vimple project, so I'm closing this.  For reference, the vimple ticket is dahu/vimple#14.
